import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import meRouter from "./me.js";
import videosRouter from "./videos.js";
import searchRouter from "./search.js";
import chatRouter from "./chat.js";
import jackSpeechRouter from "./jack-speech.js";
import competenciesRouter from "./competencies.js";
import knowledgeRouter from "./knowledge.js";
import graphRouter from "./graph.js";
import interviewRouter from "./interview.js";
import parkingLotRouter from "./parking-lot.js";
import systemHealthRouter from "./system-health.js";
import testingRouter from "./testing.js";
import testSessionsRouter from "./test-sessions.js";
import telemetryConsentRouter from "./telemetry-consent.js";
import telemetryReportsRouter from "./telemetry-reports.js";
import pilotEndOfDayRouter from "./pilot-end-of-day.js";
import activityHeartbeatRouter from "./activity-heartbeat.js";
import endOfShiftCloseoutRouter from "./end-of-shift-closeout.js";
import accountRouter from "./account.js";
import pilotEnrollmentsRouter from "./pilot-enrollments.js";
import { jackUiRequestContextMiddleware } from "../lib/jack-ui-request-context.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(meRouter);
router.use(videosRouter);
router.use(searchRouter);
router.use("/chat", jackUiRequestContextMiddleware);
router.use(chatRouter);
router.use(jackSpeechRouter);
router.use(competenciesRouter);
router.use(knowledgeRouter);
router.use(graphRouter);
router.use(interviewRouter);
router.use(parkingLotRouter);
router.use(systemHealthRouter);
router.use(testingRouter);
router.use(testSessionsRouter);
router.use(telemetryConsentRouter);
router.use(telemetryReportsRouter);
router.use(pilotEndOfDayRouter);
router.use(activityHeartbeatRouter);
router.use(endOfShiftCloseoutRouter);
router.use(accountRouter);
router.use(pilotEnrollmentsRouter);

export default router;
